// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijNdC8ak9rLqv8ms8NMeqFjUYuAs2Cgk',
    appId: '1:388385014884:web:f4b59fe5d94c82d5d00b71',
    messagingSenderId: '388385014884',
    projectId: 'quiz-app-bdapps',
    authDomain: 'quiz-app-bdapps.firebaseapp.com',
    storageBucket: 'quiz-app-bdapps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH5zikzGw6st5IoIXZuxv1nPS0sMSECBI',
    appId: '1:388385014884:android:ac55d8973a77941fd00b71',
    messagingSenderId: '388385014884',
    projectId: 'quiz-app-bdapps',
    storageBucket: 'quiz-app-bdapps.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCsS7-Q-iQo6lsuxyqKIjORqmEMLLaekk',
    appId: '1:388385014884:ios:bc3e0f29d3f035c1d00b71',
    messagingSenderId: '388385014884',
    projectId: 'quiz-app-bdapps',
    storageBucket: 'quiz-app-bdapps.firebasestorage.app',
    androidClientId: '388385014884-dokv84hgd06mjbvkcrl4pigjnub8maaj.apps.googleusercontent.com',
    iosClientId: '388385014884-omls3g3c2pqmsuvseue45j1fhsjf4knq.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
